import { 
  Cog, 
  Package, 
  ArrowRight, 
  Database, 
  GitBranch,
  Columns,
  ArrowUp,
  ArrowRightLeft,
  ArrowUpDown,
  Wrench,
  SquareStack,
  Octagon,
  MoveHorizontal,
  RotateCw,
  Eye,
} from 'lucide-react';

export interface ModuleDefinition {
  id: string;
  name: string;
  category: 'process' | 'environment' | 'actors' | 'robots' | 'pallets' | 'fmcg' | 'medical';
  icon: any;
  description: string;
  assetId?: string; // references AssetDef.id in manifest
  parameters: {
    [key: string]: {
      type: 'number' | 'string' | 'text' | 'select' | 'boolean' | 'color';
      label: string;
      default: any;
      options?: string[];
      min?: number;
      max?: number;
      step?: number;
    };
  };
}

export const moduleLibrary: ModuleDefinition[] = [
  // Process Modules
  {
    id: 'source',
    name: 'Source',
    category: 'process',
    icon: Package,
    description: 'Generates products at specified intervals',
    parameters: {
      spawnRate: {
        type: 'number',
        label: 'PPM (Products/min)',
        default: 30,
        min: 1,
        max: 600,
        step: 1,
      },
      productType: {
        type: 'select',
        label: 'Product Type',
        default: 'box',
        options: ['box', 'cylinder', 'bottle', 'pallet', 'tote'],
      },
      productLength: {
        type: 'number',
        label: 'Product Length (mm)',
        default: 300,
        min: 10,
        max: 2000,
        step: 10,
      },
      productWidth: {
        type: 'number',
        label: 'Product Width (mm)',
        default: 200,
        min: 10,
        max: 2000,
        step: 10,
      },
      productHeight: {
        type: 'number',
        label: 'Product Height (mm)',
        default: 150,
        min: 10,
        max: 2000,
        step: 10,
      },
      productColor: {
        type: 'select',
        label: 'Product Color',
        default: 'brown',
        options: ['brown', 'red', 'blue', 'green', 'yellow', 'white', 'random'],
      },
      productTextureUrl: {
        type: 'text',
        label: 'Product Texture (URL)',
        default: '',
      },
      productLabel: {
        type: 'text',
        label: 'Product Label Text',
        default: '',
      },
      labelFontSize: {
        type: 'number',
        label: 'Label Size (px)',
        default: 64,
        min: 16,
        max: 256,
        step: 8,
      },
      labelColor: {
        type: 'color',
        label: 'Label Color',
        default: '#ffffff',
      },
      maxItems: {
        type: 'number',
        label: 'Max Items (0 = unlimited)',
        default: 0,
        min: 0,
        max: 10000,
        step: 1,
      },
      runMode: { type: 'select', label: 'Run Mode', default: 'continuous', options: ['continuous', 'signal-controlled'] },
      blockedBySensorTag: { type: 'text', label: 'Blocked by Sensor Tag', default: '' },
      dwellBlockThreshold: { type: 'number', label: 'Block after Dwell (sec)', default: 3, min: 0.5, max: 60, step: 0.5 },
      resumeDelay: { type: 'number', label: 'Resume Delay (sec)', default: 0.5, min: 0, max: 30, step: 0.5 },
    },
  },
  {
    id: 'sink',
    name: 'Sink',
    category: 'process',
    icon: ArrowRight,
    description: 'Collects and removes products from the system',
    parameters: {
      capacity: {
        type: 'number',
        label: 'Capacity',
        default: 1000,
        min: 1,
        max: 10000,
        step: 1,
      },
      showCounter: {
        type: 'boolean',
        label: 'Show Counter',
        default: true,
      },
    },
  },
  {
    id: 'belt-conveyor',
    name: 'Belt Conveyor',
    category: 'process',
    icon: ArrowRight,
    description: 'Parametric conveyor — belt, roller, or modular with adjustable dimensions',
    assetId: 'belt-conveyor',
    parameters: {
      conveyorType: { type: 'select', label: 'Conveyor Type', default: 'belt', options: ['belt', 'roller', 'modular', 'cleated'] },
      drivePosition: { type: 'select', label: 'Drive Type', default: 'end', options: ['end', 'center'] },
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 200, max: 1500, step: 50 },
      length: { type: 'number', label: 'Length (mm)', default: 3000, min: 500, max: 15000, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 800, min: 300, max: 3000, step: 50 },
      inclineAngle: { type: 'number', label: 'Incline Angle (°)', default: 0, min: 0, max: 35, step: 1 },
      beltSpeed: { type: 'number', label: 'Speed (m/min)', default: 20, min: 1, max: 120, step: 1 },
      beltColor: { type: 'color', label: 'Belt Color', default: '#1e1e1e' },
      frameColor: { type: 'color', label: 'Frame Color', default: '#c0c0c0' },
      motorSide: { type: 'select', label: 'Motor Side', default: 'right', options: ['left', 'right'] },
      sideGuides: { type: 'boolean', label: 'Side Guides', default: false },
      guideHeight: { type: 'number', label: 'Guide Height (mm)', default: 60, min: 20, max: 200, step: 10 },
      supportSpacing: { type: 'number', label: 'Support Spacing (mm)', default: 1500, min: 500, max: 4000, step: 100 },
      showLegs: { type: 'boolean', label: 'Show Supports', default: true },
      supportType: { type: 'select', label: 'Support Type', default: 'floor', options: ['floor', 'overhang', 'cantilever', 'ceiling-hanger'] },
      adjustableFeetEnabled: { type: 'boolean', label: 'Adjustable Feet', default: true },
      ceilingHeight: { type: 'number', label: 'Ceiling Height (mm)', default: 3000, min: 1500, max: 6000, step: 100 },
      hangerStyle: { type: 'select', label: 'Hanger Style', default: 'twin-rod', options: ['single-rod', 'twin-rod'] },
      hangerCrossbar: { type: 'boolean', label: 'Hanger Crossbar', default: true },
      accumulationMode: { type: 'boolean', label: 'Accumulation Mode', default: false },
      accumulationZones: { type: 'number', label: 'Accumulation Zones', default: 6, min: 2, max: 20, step: 1 },
      cleatHeight: { type: 'number', label: 'Cleat Height (mm)', default: 25, min: 10, max: 80, step: 5 },
      cleatSpacing: { type: 'number', label: 'Cleat Spacing (mm)', default: 150, min: 50, max: 500, step: 25 },
      cleatStyle: { type: 'select', label: 'Cleat Style', default: 'straight', options: ['straight', 'chevron', 'angled'] },
      sidewallEnabled: { type: 'boolean', label: 'Sidewalls', default: false },
      sidewallHeight: { type: 'number', label: 'Sidewall Height (mm)', default: 80, min: 30, max: 200, step: 10 },
    },
  },
  {
    id: 'bend-conveyor',
    name: 'Bend Conveyor',
    category: 'process',
    icon: RotateCw,
    description: 'Curved conveyor for direction changes — 30°, 45°, 60°, 90°, or 180° bends',
    assetId: 'bend-conveyor',
    parameters: {
      bendAngle: { type: 'select', label: 'Bend Angle (°)', default: '90', options: ['30', '45', '60', '90', '180'] },
      bendDirection: { type: 'select', label: 'Bend Direction', default: 'right', options: ['left', 'right'] },
      surfaceType: { type: 'select', label: 'Surface Type', default: 'belt', options: ['belt', 'roller', 'modular'] },
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 200, max: 1200, step: 50 },
      radius: { type: 'number', label: 'Bend Radius (mm)', default: 1000, min: 400, max: 4000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 800, min: 300, max: 3000, step: 50 },
      speed: { type: 'number', label: 'Speed (m/min)', default: 20, min: 1, max: 120, step: 1 },
      beltColor: { type: 'color', label: 'Belt Color', default: '#1e1e1e' },
      frameColor: { type: 'color', label: 'Frame Color', default: '#c0c0c0' },
      sideGuides: { type: 'boolean', label: 'Side Guides', default: true },
      guideHeight: { type: 'number', label: 'Guide Height (mm)', default: 60, min: 20, max: 200, step: 10 },
      showLegs: { type: 'boolean', label: 'Show Supports', default: true },
      supportType: { type: 'select', label: 'Support Type', default: 'floor', options: ['floor', 'overhang', 'cantilever', 'ceiling-hanger'] },
      supportSpacing: { type: 'number', label: 'Support Spacing (°)', default: 45, min: 15, max: 90, step: 15 },
      adjustableFeetEnabled: { type: 'boolean', label: 'Adjustable Feet', default: true },
    },
  },
  {
    id: 'spiral-conveyor',
    name: 'Spiral Conveyor',
    category: 'process',
    icon: RotateCw,
    description: 'Premium AmbaFlex-style spiral conveyor for vertical transport',
    assetId: 'spiral-conveyor',
    parameters: {
      direction: { type: 'select', label: 'Direction', default: 'up', options: ['up', 'down'] },
      beltWidth: { type: 'number', label: 'Belt Width (mm)', default: 400, min: 150, max: 800, step: 50 },
      diameter: { type: 'number', label: 'Diameter (mm)', default: 1800, min: 800, max: 4000, step: 100 },
      totalHeight: { type: 'number', label: 'Total Height (mm)', default: 3000, min: 500, max: 12000, step: 100 },
      turns: { type: 'number', label: 'Turns', default: 3, min: 0.5, max: 10, step: 0.5 },
      risePerTurn: { type: 'number', label: 'Rise Per Turn (mm)', default: 1000, min: 200, max: 3000, step: 50 },
      infeedAngle: { type: 'number', label: 'Infeed Angle (°)', default: 0, min: 0, max: 360, step: 15 },
      outfeedAngle: { type: 'number', label: 'Outfeed Angle (°)', default: 180, min: 0, max: 360, step: 15 },
      speed: { type: 'number', label: 'Speed (m/min)', default: 20, min: 1, max: 60, step: 1 },
      beltColor: { type: 'color', label: 'Belt Color', default: '#1e1e1e' },
      frameColor: { type: 'color', label: 'Frame Color', default: '#c0c0c0' },
      sideGuides: { type: 'boolean', label: 'Side Guides', default: true },
      guideHeight: { type: 'number', label: 'Guide Height (mm)', default: 100, min: 40, max: 250, step: 10 },
      showLegs: { type: 'boolean', label: 'Show Supports', default: true },
      supportStyle: { type: 'select', label: 'Support Style', default: 'standard', options: ['standard', 'heavy-duty'] },
      baseType: { type: 'select', label: 'Base Type', default: 'reinforced', options: ['compact', 'reinforced'] },
      centerStructure: { type: 'select', label: 'Center Structure', default: 'column', options: ['column', 'framed-core'] },
    },
  },
  {
    id: 'stopper',
    name: 'Stopper',
    category: 'process',
    icon: Octagon,
    description: 'Pneumatic pop-up blade stop — halts product flow on conveyor',
    assetId: 'stopper',
    parameters: {
      enabled: { type: 'boolean', label: 'Enabled', default: true },
      engaged: { type: 'boolean', label: 'Engaged', default: true },
      width: { type: 'number', label: 'Belt Width (mm)', default: 400, min: 200, max: 1200, step: 50 },
      bladeHeight: { type: 'number', label: 'Blade Height (mm)', default: 80, min: 30, max: 200, step: 10 },
      mountHeight: { type: 'number', label: 'Mount Height (mm)', default: 800, min: 300, max: 3000, step: 50 },
      stopperMode: { type: 'select', label: 'Mode', default: 'sensor-triggered', options: ['always-stop', 'sensor-triggered', 'timed-release', 'timed-batch', 'downstream-clear'] },
      triggerSensorTag: { type: 'text', label: 'Trigger Sensor Tag', default: '' },
      stopCondition: { type: 'select', label: 'Stop Condition', default: 'any-product', options: ['any-product', 'sensor-true', 'sensor-color', 'sensor-type'] },
      releaseCondition: { type: 'select', label: 'Release Condition', default: 'timed', options: ['timed', 'count', 'downstream-clear', 'sensor-clear', 'sensor-dwell'] },
      holdTime: { type: 'number', label: 'Hold Time (sec)', default: 3, min: 0.1, max: 120, step: 0.5 },
      releaseCount: { type: 'number', label: 'Release Count', default: 1, min: 1, max: 50, step: 1 },
      releaseDelay: { type: 'number', label: 'Release Delay (sec)', default: 0, min: 0, max: 30, step: 0.5 },
      stopCount: { type: 'number', label: 'Stop Count (0=unlimited)', default: 0, min: 0, max: 100, step: 1 },
      secondarySensorTag: { type: 'text', label: 'Secondary Sensor Tag (queue)', default: '' },
      mountPosition: { type: 'number', label: 'Position Along Path', default: 0.5, min: 0, max: 1, step: 0.05 },
      mountSide: { type: 'select', label: 'Mount Side', default: 'center', options: ['left', 'right', 'center'] },
      heightOffset: { type: 'number', label: 'Height Offset (mm)', default: 0, min: -200, max: 200, step: 10 },
      flip: { type: 'boolean', label: 'Flip 180°', default: false },
    },
  },
  {
    id: 'pusher',
    name: 'Pusher',
    category: 'process',
    icon: MoveHorizontal,
    description: 'Pneumatic side-push diverter for reject or lane transfer',
    assetId: 'pusher',
    parameters: {
      enabled: { type: 'boolean', label: 'Enabled', default: true },
      side: { type: 'select', label: 'Push Side', default: 'right', options: ['left', 'right'] },
      stroke: { type: 'number', label: 'Stroke (mm)', default: 300, min: 100, max: 600, step: 50 },
      plateWidth: { type: 'number', label: 'Plate Width (mm)', default: 250, min: 100, max: 500, step: 50 },
      plateHeight: { type: 'number', label: 'Plate Height (mm)', default: 100, min: 50, max: 200, step: 10 },
      mountHeight: { type: 'number', label: 'Mount Height (mm)', default: 800, min: 300, max: 3000, step: 50 },
      extended: { type: 'boolean', label: 'Extended', default: false },
      pusherMode: { type: 'select', label: 'Pusher Mode', default: 'reject-all', options: ['reject-all', 'divert-by-color', 'divert-by-type', 'divert-alternating'] },
      targetColor: { type: 'select', label: 'Target Color', default: 'red', options: ['red', 'blue', 'green', 'yellow', 'white'] },
      targetProductType: { type: 'select', label: 'Target Product Type', default: 'box', options: ['box', 'cylinder', 'bottle', 'tote', 'pallet'] },
      cycleTime: { type: 'number', label: 'Cycle Time (sec)', default: 1.0, min: 0.2, max: 10, step: 0.1 },
      routeBy: { type: 'select', label: 'Route By', default: 'always', options: ['always', 'color-match', 'type-match', 'size-match', 'sensor-trigger'] },
      routeValues: { type: 'string', label: 'Route Match Values (comma-sep)', default: '' },
      invertMatch: { type: 'boolean', label: 'Invert Match', default: false },
      autoRetract: { type: 'boolean', label: 'Auto Retract', default: true },
      mountPosition: { type: 'number', label: 'Position Along Path', default: 0.5, min: 0, max: 1, step: 0.05 },
      heightOffset: { type: 'number', label: 'Height Offset (mm)', default: 0, min: -200, max: 200, step: 10 },
      flip: { type: 'boolean', label: 'Flip 180°', default: false },
    },
  },
  {
    id: 'sensor',
    name: 'Sensor',
    category: 'process',
    icon: Eye,
    description: 'Photoelectric sensor for product detection — through-beam, retro-reflective, or diffuse',
    assetId: 'sensor',
    parameters: {
      sensorTag: { type: 'text', label: 'Sensor Tag', default: '' },
      sensorType: { type: 'select', label: 'Sensor Type', default: 'through-beam', options: ['through-beam', 'retro-reflective', 'diffuse'] },
      triggered: { type: 'boolean', label: 'Triggered', default: false },
      mountHeight: { type: 'number', label: 'Mount Height (mm)', default: 800, min: 300, max: 3000, step: 50 },
      sensorHeight: { type: 'number', label: 'Height Above Belt (mm)', default: 80, min: 20, max: 300, step: 10 },
      beltWidth: { type: 'number', label: 'Belt Width (mm)', default: 600, min: 200, max: 1200, step: 50 },
      showBeam: { type: 'boolean', label: 'Show Beam', default: true },
      detectionRange: { type: 'number', label: 'Detection Range (mm)', default: 300, min: 50, max: 1000, step: 50 },
      detectColor: { type: 'boolean', label: 'Detect Color', default: false },
      detectType: { type: 'boolean', label: 'Detect Type', default: false },
      detectSize: { type: 'boolean', label: 'Detect Size', default: false },
      colorFilter: { type: 'string', label: 'Color Filter (comma-sep)', default: '' },
      typeFilter: { type: 'string', label: 'Type Filter (comma-sep)', default: '' },
      cooldown: { type: 'number', label: 'Cooldown (sec)', default: 0, min: 0, max: 10, step: 0.1 },
      debounce: { type: 'number', label: 'Debounce (sec)', default: 0, min: 0, max: 5, step: 0.1 },
      dwellTimeThreshold: { type: 'number', label: 'Dwell Time Threshold (sec)', default: 0, min: 0, max: 60, step: 0.5 },
      onDwellEvent: { type: 'select', label: 'On Dwell Event', default: 'none', options: ['none', 'stop-source', 'release-stopper', 'stop-source-and-release'] },
      mountPosition: { type: 'number', label: 'Position Along Path', default: 0.5, min: 0, max: 1, step: 0.05 },
      mountSide: { type: 'select', label: 'Mount Side', default: 'center', options: ['left', 'right', 'center'] },
      heightOffset: { type: 'number', label: 'Height Offset (mm)', default: 0, min: -200, max: 200, step: 10 },
      flip: { type: 'boolean', label: 'Flip 180°', default: false },
    },
  },
  {
    id: 'buffer',
    name: 'Buffer',
    category: 'process',
    icon: Database,
    description: 'Stores products temporarily, providing accumulation',
    parameters: {
      capacity: {
        type: 'number',
        label: 'Capacity',
        default: 10,
        min: 1,
        max: 100,
        step: 1,
      },
      width: {
        type: 'number',
        label: 'Width (mm)',
        default: 2000,
        min: 1000,
        max: 5000,
        step: 500,
      },
      length: {
        type: 'number',
        label: 'Length (mm)',
        default: 3000,
        min: 1000,
        max: 10000,
        step: 500,
      },
    },
  },
  {
    id: 'machine',
    name: 'Machine / Station',
    category: 'process',
    icon: Cog,
    description: 'Industrial processing station with configurable size',
    parameters: {
      machineWidth: { type: 'number', label: 'Width (mm)', default: 1500, min: 500, max: 5000, step: 100 },
      machineLength: { type: 'number', label: 'Length (mm)', default: 2000, min: 500, max: 5000, step: 100 },
      machineHeight: { type: 'number', label: 'Height (mm)', default: 1800, min: 500, max: 3000, step: 100 },
      processingTime: {
        type: 'number',
        label: 'Processing Time (s)',
        default: 5.0,
        min: 0.1,
        max: 60.0,
        step: 0.1,
      },
      capacity: {
        type: 'number',
        label: 'Capacity',
        default: 1,
        min: 1,
        max: 10,
        step: 1,
      },
      failureRate: {
        type: 'number',
        label: 'Failure Rate (%)',
        default: 0,
        min: 0,
        max: 50,
        step: 1,
      },
      statusLight: {
        type: 'boolean',
        label: 'Show Status Light',
        default: true,
      },
    },
  },
  {
    id: 'router',
    name: 'Router',
    category: 'process',
    icon: GitBranch,
    description: 'Routes products to different destinations',
    parameters: {
      mode: {
        type: 'select',
        label: 'Routing Mode',
        default: 'round-robin',
        options: ['round-robin', 'priority', 'shortest-queue', 'random'],
      },
      outputs: {
        type: 'number',
        label: 'Number of Outputs',
        default: 2,
        min: 2,
        max: 4,
        step: 1,
      },
    },
  },
  {
    id: 'transfer-bridge',
    name: 'Transfer Bridge',
    category: 'process',
    icon: Columns,
    description: 'Gap bridge connecting two conveyors',
    assetId: 'transfer-bridge',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 300, max: 1200, step: 50 },
      length: { type: 'number', label: 'Length (mm)', default: 1000, min: 200, max: 2000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 800, min: 300, max: 1500, step: 50 },
    },
  },
  {
    id: 'popup-transfer',
    name: 'Pop-Up Transfer',
    category: 'process',
    icon: ArrowUp,
    description: 'Conveyor with pop-up chains/rollers for 90° transfer',
    assetId: 'popup-transfer',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 300, max: 1200, step: 50 },
      length: { type: 'number', label: 'Length (mm)', default: 1500, min: 500, max: 3000, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 800, min: 300, max: 1500, step: 50 },
      popupHeight: { type: 'number', label: 'Popup Height (mm)', default: 200, min: 100, max: 500, step: 10 },
      speed: { type: 'number', label: 'Speed (m/min)', default: 20, min: 1, max: 100, step: 1 },
      direction: { type: 'select', label: 'Direction', default: 'left', options: ['left', 'right'] },
    },
  },
  {
    id: 'pusher-transfer',
    name: 'Pusher Transfer',
    category: 'process',
    icon: ArrowRightLeft,
    description: 'Conveyor with side-mounted pusher arm',
    assetId: 'pusher-transfer',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 300, max: 1200, step: 50 },
      length: { type: 'number', label: 'Length (mm)', default: 2000, min: 500, max: 4000, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 800, min: 300, max: 1500, step: 50 },
      pushAngle: { type: 'number', label: 'Push Angle (°)', default: 90, min: 30, max: 180, step: 5 },
      pushForce: { type: 'number', label: 'Push Force', default: 1, min: 0.1, max: 5, step: 0.1 },
      pushSide: { type: 'select', label: 'Push Side', default: 'left', options: ['left', 'right'] },
    },
  },
  {
    id: 'merge-divert',
    name: 'Merge/Divert',
    category: 'process',
    icon: GitBranch,
    description: 'Y-junction for merging or splitting flow',
    assetId: 'merge-divert',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 300, max: 1200, step: 50 },
      mainLength: { type: 'number', label: 'Main Length (mm)', default: 3000, min: 1000, max: 6000, step: 100 },
      branchLength: { type: 'number', label: 'Branch Length (mm)', default: 2000, min: 500, max: 4000, step: 100 },
      branchAngle: { type: 'number', label: 'Branch Angle (°)', default: 30, min: 15, max: 90, step: 5 },
      height: { type: 'number', label: 'Height (mm)', default: 800, min: 300, max: 1500, step: 50 },
      mode: { type: 'select', label: 'Mode', default: 'divert', options: ['merge', 'divert'] },
    },
  },
  {
    id: 'vertical-lifter',
    name: 'Vertical Lifter',
    category: 'process',
    icon: ArrowUpDown,
    description: 'Elevator for vertical product movement',
    assetId: 'vertical-lifter',
    parameters: {
      platformWidth: { type: 'number', label: 'Platform Width (mm)', default: 1000, min: 500, max: 2000, step: 50 },
      platformDepth: { type: 'number', label: 'Platform Depth (mm)', default: 1000, min: 500, max: 2000, step: 50 },
      liftHeight: { type: 'number', label: 'Lift Height (mm)', default: 3000, min: 500, max: 10000, step: 100 },
      liftDirection: { type: 'select', label: 'Lift Direction', default: 'up', options: ['up', 'down'] },
      speed: { type: 'number', label: 'Speed (m/min)', default: 20, min: 1, max: 100, step: 1 },
      loadDirection: { type: 'select', label: 'Load Direction', default: 'front', options: ['front', 'back', 'left', 'right'] },
      capacity: { type: 'number', label: 'Capacity', default: 4, min: 1, max: 20, step: 1 },
    },
  },
  {
    id: 'pick-and-place',
    name: 'Pick & Place Robot',
    category: 'process',
    icon: Wrench,
    description: 'Robotic arm for picking and placing products',
    parameters: {
      reach: {
        type: 'number',
        label: 'Reach Radius (mm)',
        default: 3000,
        min: 1000,
        max: 6000,
        step: 500,
      },
      speed: {
        type: 'number',
        label: 'Movement Speed (m/min)',
        default: 60,
        min: 5,
        max: 180,
        step: 5,
      },
      gripTime: {
        type: 'number',
        label: 'Grip Time (s)',
        default: 0.5,
        min: 0.1,
        max: 2.0,
        step: 0.1,
      },
      accuracy: {
        type: 'number',
        label: 'Accuracy (%)',
        default: 99,
        min: 80,
        max: 100,
        step: 1,
      },
    },
  },
  {
    id: 'palletizer',
    name: 'Palletizer',
    category: 'process',
    icon: SquareStack,
    description: 'Automated palletizing system for stacking products',
    parameters: {
      palletWidth: {
        type: 'number',
        label: 'Pallet Width (mm)',
        default: 1200,
        min: 800,
        max: 2000,
        step: 50,
      },
      palletLength: {
        type: 'number',
        label: 'Pallet Length (mm)',
        default: 800,
        min: 600,
        max: 1500,
        step: 50,
      },
      stackHeight: {
        type: 'number',
        label: 'Max Stack Height (mm)',
        default: 1500,
        min: 500,
        max: 3000,
        step: 100,
      },
      cycleTime: {
        type: 'number',
        label: 'Cycle Time (s)',
        default: 3.0,
        min: 1.0,
        max: 10.0,
        step: 0.5,
      },
    },
  },

  // Environment Modules
  {
    id: 'wall',
    name: 'Wall',
    category: 'environment',
    icon: Package,
    description: 'Structural wall element',
    assetId: 'wall',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 5000, min: 500, max: 20000, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 3000, min: 1000, max: 8000, step: 100 },
      thickness: { type: 'number', label: 'Thickness (mm)', default: 200, min: 100, max: 500, step: 10 },
      wallColor: { type: 'color', label: 'Wall Color', default: '#e8e8e8' },
      textureUrl: { type: 'text', label: 'Wall Texture (URL)', default: '' },
      wallLabel: { type: 'text', label: 'Wall Label Text', default: '' },
      labelFontSize: { type: 'number', label: 'Label Size (px)', default: 128, min: 32, max: 512, step: 16 },
      labelColor: { type: 'color', label: 'Label Color', default: '#333333' },
    },
  },
  {
    id: 'door',
    name: 'Door',
    category: 'environment',
    icon: Package,
    description: 'Door with frame',
    assetId: 'door',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1200, min: 600, max: 3000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 2400, min: 1800, max: 3000, step: 50 },
      thickness: { type: 'number', label: 'Thickness (mm)', default: 100, min: 50, max: 200, step: 10 },
    },
  },
  {
    id: 'window',
    name: 'Window',
    category: 'environment',
    icon: Package,
    description: 'Window with frame and glass',
    assetId: 'window',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1500, min: 400, max: 4000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 1200, min: 400, max: 3000, step: 50 },
      thickness: { type: 'number', label: 'Thickness (mm)', default: 100, min: 50, max: 200, step: 10 },
    },
  },
  {
    id: 'stairs',
    name: 'Stairs',
    category: 'environment',
    icon: Package,
    description: 'Staircase with configurable steps',
    assetId: 'stairs',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1200, min: 600, max: 3000, step: 50 },
      stepCount: { type: 'number', label: 'Steps', default: 12, min: 3, max: 30, step: 1 },
      stepHeight: { type: 'number', label: 'Step Height (mm)', default: 180, min: 150, max: 220, step: 10 },
      stepDepth: { type: 'number', label: 'Step Depth (mm)', default: 280, min: 200, max: 350, step: 10 },
    },
  },
  {
    id: 'pallet-rack',
    name: 'Pallet Rack',
    category: 'environment',
    icon: Package,
    description: 'Industrial pallet racking',
    assetId: 'pallet-rack',
    parameters: {
      bayWidth: { type: 'number', label: 'Bay Width (mm)', default: 2700, min: 1500, max: 4000, step: 100 },
      depth: { type: 'number', label: 'Depth (mm)', default: 1100, min: 800, max: 1500, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 5000, min: 2000, max: 12000, step: 100 },
      levels: { type: 'number', label: 'Levels', default: 4, min: 2, max: 8, step: 1 },
    },
  },
  {
    id: 'safety-rail',
    name: 'Safety Rail',
    category: 'environment',
    icon: Package,
    description: 'Safety guardrail',
    assetId: 'safety-rail',
    parameters: {
      width: { type: 'number', label: 'Length (mm)', default: 3000, min: 500, max: 10000, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 1100, min: 900, max: 1200, step: 50 },
      thickness: { type: 'number', label: 'Thickness (mm)', default: 60, min: 40, max: 80, step: 10 },
    },
  },
  {
    id: 'warehouse-shell',
    name: 'Warehouse Shell',
    category: 'environment',
    icon: Package,
    description: 'Large warehouse enclosure',
    assetId: 'warehouse-shell',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 20000, min: 5000, max: 50000, step: 500 },
      height: { type: 'number', label: 'Height (mm)', default: 8000, min: 4000, max: 15000, step: 500 },
      thickness: { type: 'number', label: 'Thickness (mm)', default: 300, min: 200, max: 500, step: 50 },
    },
  },

  {
    id: 'pallet',
    name: 'Pallet',
    category: 'environment',
    icon: Package,
    description: 'Standard EUR pallet',
    parameters: {},
  },
  {
    id: 'cardboard-box',
    name: 'Cardboard Box',
    category: 'environment',
    icon: Package,
    description: 'Cardboard shipping box',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 400, min: 100, max: 1000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 300, min: 100, max: 800, step: 50 },
      depth: { type: 'number', label: 'Depth (mm)', default: 300, min: 100, max: 800, step: 50 },
    },
  },
  {
    id: 'fence',
    name: 'Safety Fence',
    category: 'environment',
    icon: Package,
    assetId: 'fence',
    description: 'Machine guard / safety fence panel',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 2000, min: 500, max: 6000, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 2000, min: 1000, max: 3000, step: 100 },
    },
  },
  {
    id: 'fence-gate',
    name: 'Fence Gate',
    category: 'environment',
    icon: Package,
    assetId: 'fence-gate',
    description: 'Access gate in safety fence',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1200, min: 600, max: 2000, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 2000, min: 1000, max: 3000, step: 100 },
    },
  },
  {
    id: 'bollard',
    name: 'Bollard',
    category: 'environment',
    icon: Package,
    assetId: 'bollard',
    description: 'Safety bollard / post',
    parameters: {},
  },
  {
    id: 'operator-station',
    name: 'Operator Station',
    category: 'environment',
    icon: Package,
    assetId: 'operator-station',
    description: 'Packing bench / operator workstation with monitor',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1500, min: 800, max: 3000, step: 100 },
      depth: { type: 'number', label: 'Depth (mm)', default: 800, min: 400, max: 1200, step: 100 },
    },
  },
  {
    id: 'electrical-cabinet',
    name: 'Electrical Cabinet',
    category: 'environment',
    icon: Package,
    assetId: 'electrical-cabinet',
    description: 'Electrical panel / control cabinet',
    parameters: {},
  },
  {
    id: 'tower-light',
    name: 'Tower Light',
    category: 'environment',
    icon: Package,
    assetId: 'tower-light',
    description: 'Stack light / warning beacon (red-amber-green)',
    parameters: {},
  },
  {
    id: 'pallet-stack',
    name: 'Pallet Stack',
    category: 'environment',
    icon: Package,
    assetId: 'pallet-stack',
    description: 'Stack of empty pallets',
    parameters: {
      stackCount: { type: 'number', label: 'Stack Count', default: 5, min: 1, max: 12, step: 1 },
    },
  },
  {
    id: 'floor-zone',
    name: 'Floor Zone',
    category: 'environment',
    icon: Package,
    assetId: 'floor-zone',
    description: 'Floor marking / work zone indicator',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 4000, min: 1000, max: 20000, step: 500 },
      depth: { type: 'number', label: 'Depth (mm)', default: 4000, min: 1000, max: 20000, step: 500 },
      zoneColor: { type: 'select', label: 'Zone Color', default: 'yellow', options: ['yellow', 'green', 'red', 'blue', 'white'] },
    },
  },
  {
    id: 'hmi-stand',
    name: 'HMI Stand',
    category: 'environment',
    icon: Package,
    assetId: 'hmi-stand',
    description: 'Touchscreen HMI control panel on stand',
    parameters: {},
  },
  {
    id: 'machine-enclosure',
    name: 'Machine Enclosure',
    category: 'environment',
    icon: Package,
    assetId: 'machine-enclosure',
    description: 'Enclosed machine cell / cabinet',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 2000, min: 800, max: 5000, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 2500, min: 1500, max: 4000, step: 100 },
      depth: { type: 'number', label: 'Depth (mm)', default: 2000, min: 800, max: 5000, step: 100 },
    },
  },
  {
    id: 'stretch-wrapper',
    name: 'Stretch Wrapper',
    category: 'environment',
    icon: Package,
    description: 'Pallet stretch wrapping machine',
    parameters: {},
  },

  // Actor Modules
  {
    id: 'operator',
    name: 'Operator',
    category: 'actors',
    icon: Package, // Replace with appropriate icon
    description: 'Human operator worker',
    parameters: {
      walkSpeed: {
        type: 'number',
        label: 'Walk Speed (m/min)',
        default: 90,
        min: 30,
        max: 180,
        step: 5,
      },
      color: {
        type: 'color',
        label: 'Uniform Color',
        default: '#4f46e5',
      },
      skillLevel: {
        type: 'select',
        label: 'Skill Level',
        default: 'medium',
        options: ['low', 'medium', 'high', 'expert'],
      },
    },
  },

  {
    id: 'forklift',
    name: 'Forklift',
    category: 'actors',
    icon: Package, // Replace with appropriate icon
    description: 'Industrial forklift vehicle',
    parameters: {
      speed: {
        type: 'number',
        label: 'Travel Speed (m/min)',
        default: 180,
        min: 60,
        max: 480,
        step: 10,
      },
      liftHeight: {
        type: 'number',
        label: 'Max Lift Height (mm)',
        default: 4000,
        min: 2000,
        max: 8000,
        step: 500,
      },
      capacity: {
        type: 'number',
        label: 'Load Capacity (kg)',
        default: 2000,
        min: 500,
        max: 5000,
        step: 100,
      },
      fuelLevel: {
        type: 'number',
        label: 'Fuel Level (%)',
        default: 100,
        min: 0,
        max: 100,
        step: 1,
      },
    },
  },

  {
    id: 'agv',
    name: 'AGV',
    category: 'actors',
    icon: Package, // Replace with appropriate icon
    description: 'Automated Guided Vehicle',
    parameters: {
      speed: {
        type: 'number',
        label: 'Travel Speed (m/min)',
        default: 120,
        min: 30,
        max: 300,
        step: 10,
      },
      capacity: {
        type: 'number',
        label: 'Load Capacity (kg)',
        default: 500,
        min: 50,
        max: 2000,
        step: 50,
      },
      batteryLevel: {
        type: 'number',
        label: 'Battery Level (%)',
        default: 100,
        min: 0,
        max: 100,
        step: 1,
      },
      pathFinding: {
        type: 'select',
        label: 'Path Finding',
        default: 'shortest',
        options: ['shortest', 'safest', 'efficient'],
      },
    },
  },
  {
    id: 'pallet-truck',
    name: 'Pallet Truck',
    category: 'actors',
    icon: Package,
    description: 'Manual pallet truck / pump truck',
    parameters: {
      speed: {
        type: 'number',
        label: 'Speed (m/min)',
        default: 90,
        min: 30,
        max: 180,
        step: 5,
      },
    },
  },

  // ─── Robots ───────────────────────────────────────────────────
  {
    id: 'cartesian-robot',
    name: 'Cartesian Robot',
    category: 'robots',
    icon: MoveHorizontal,
    description: 'Gantry-style linear axis robot for pick-and-place and palletizing',
    parameters: {
      reachX: { type: 'number', label: 'X Travel (mm)', default: 2000, min: 500, max: 6000, step: 100 },
      reachY: { type: 'number', label: 'Y Travel (mm)', default: 1500, min: 500, max: 4000, step: 100 },
      reachZ: { type: 'number', label: 'Z Travel (mm)', default: 1000, min: 300, max: 3000, step: 100 },
      baseHeight: { type: 'number', label: 'Base Height (mm)', default: 2500, min: 1500, max: 4000, step: 100 },
      cycleTime: { type: 'number', label: 'Cycle Time (s)', default: 4, min: 1, max: 30, step: 0.5 },
      speedFactor: { type: 'number', label: 'Speed Factor', default: 1, min: 0.1, max: 3, step: 0.1 },
      toolType: { type: 'select', label: 'Tool Type', default: 'vacuum', options: ['vacuum', 'gripper', 'magnetic'] },
      pedestalEnabled: { type: 'boolean', label: 'Pedestal', default: false },
      pedestalHeight: { type: 'number', label: 'Pedestal Height (mm)', default: 500, min: 0, max: 2000, step: 100 },
      pickHeight: { type: 'number', label: 'Pick Height (mm)', default: 800, min: 0, max: 3000, step: 50 },
      placeHeight: { type: 'number', label: 'Place Height (mm)', default: 800, min: 0, max: 3000, step: 50 },
    },
  },
  {
    id: 'cobot',
    name: 'Collaborative Robot',
    category: 'robots',
    icon: RotateCw,
    description: 'Modern collaborative robot arm for safe human-robot interaction',
    parameters: {
      reach: { type: 'number', label: 'Reach (mm)', default: 850, min: 500, max: 1300, step: 50 },
      payload: { type: 'number', label: 'Payload (kg)', default: 10, min: 3, max: 25, step: 1 },
      baseHeight: { type: 'number', label: 'Base Height (mm)', default: 200, min: 100, max: 500, step: 50 },
      cycleTime: { type: 'number', label: 'Cycle Time (s)', default: 3, min: 1, max: 20, step: 0.5 },
      speedFactor: { type: 'number', label: 'Speed Factor', default: 1, min: 0.1, max: 3, step: 0.1 },
      toolType: { type: 'select', label: 'Tool Type', default: 'gripper', options: ['vacuum', 'gripper', 'magnetic'] },
      pedestalEnabled: { type: 'boolean', label: 'Pedestal', default: true },
      pedestalHeight: { type: 'number', label: 'Pedestal Height (mm)', default: 800, min: 0, max: 2000, step: 100 },
      pickHeight: { type: 'number', label: 'Pick Height (mm)', default: 800, min: 0, max: 3000, step: 50 },
      placeHeight: { type: 'number', label: 'Place Height (mm)', default: 800, min: 0, max: 3000, step: 50 },
    },
  },
  {
    id: 'robot-5axis',
    name: '5-Axis Robot',
    category: 'robots',
    icon: Wrench,
    description: 'Industrial 5-axis articulated robot for high-speed handling',
    parameters: {
      reach: { type: 'number', label: 'Reach (mm)', default: 1400, min: 700, max: 3000, step: 50 },
      payload: { type: 'number', label: 'Payload (kg)', default: 25, min: 5, max: 120, step: 5 },
      baseHeight: { type: 'number', label: 'Base Height (mm)', default: 400, min: 200, max: 800, step: 50 },
      cycleTime: { type: 'number', label: 'Cycle Time (s)', default: 3, min: 0.5, max: 20, step: 0.5 },
      speedFactor: { type: 'number', label: 'Speed Factor', default: 1, min: 0.1, max: 3, step: 0.1 },
      toolType: { type: 'select', label: 'Tool Type', default: 'gripper', options: ['vacuum', 'gripper', 'magnetic', 'weld'] },
      pedestalEnabled: { type: 'boolean', label: 'Pedestal', default: false },
      pedestalHeight: { type: 'number', label: 'Pedestal Height (mm)', default: 0, min: 0, max: 2000, step: 100 },
      pickHeight: { type: 'number', label: 'Pick Height (mm)', default: 800, min: 0, max: 3000, step: 50 },
      placeHeight: { type: 'number', label: 'Place Height (mm)', default: 800, min: 0, max: 3000, step: 50 },
    },
  },
  {
    id: 'robot-6axis',
    name: '6-Axis Robot',
    category: 'robots',
    icon: Cog,
    description: 'Premium 6-axis industrial robot for complex automation tasks',
    parameters: {
      reach: { type: 'number', label: 'Reach (mm)', default: 2000, min: 900, max: 4000, step: 50 },
      payload: { type: 'number', label: 'Payload (kg)', default: 60, min: 10, max: 300, step: 10 },
      baseHeight: { type: 'number', label: 'Base Height (mm)', default: 500, min: 300, max: 1000, step: 50 },
      cycleTime: { type: 'number', label: 'Cycle Time (s)', default: 4, min: 0.5, max: 30, step: 0.5 },
      speedFactor: { type: 'number', label: 'Speed Factor', default: 1, min: 0.1, max: 3, step: 0.1 },
      toolType: { type: 'select', label: 'Tool Type', default: 'gripper', options: ['vacuum', 'gripper', 'magnetic', 'weld'] },
      pedestalEnabled: { type: 'boolean', label: 'Pedestal', default: true },
      pedestalHeight: { type: 'number', label: 'Pedestal Height (mm)', default: 600, min: 0, max: 3000, step: 100 },
      pickHeight: { type: 'number', label: 'Pick Height (mm)', default: 800, min: 0, max: 3000, step: 50 },
      placeHeight: { type: 'number', label: 'Place Height (mm)', default: 800, min: 0, max: 3000, step: 50 },
      approachHeight: { type: 'number', label: 'Approach Height (mm)', default: 300, min: 50, max: 1000, step: 50 },
      pickDelay: { type: 'number', label: 'Pick Delay (s)', default: 0.3, min: 0, max: 5, step: 0.1 },
      placeDelay: { type: 'number', label: 'Place Delay (s)', default: 0.3, min: 0, max: 5, step: 0.1 },
    },
  },

  // ─── Pallets ─────────────────────────────────────────────────
  {
    id: 'eur-pallet',
    name: 'EUR Pallet',
    category: 'pallets',
    icon: SquareStack,
    description: 'Standard EUR/EPAL pallet (1200×800mm)',
    parameters: {
      length: { type: 'number', label: 'Length (mm)', default: 1200, min: 800, max: 1600, step: 50 },
      width: { type: 'number', label: 'Width (mm)', default: 800, min: 600, max: 1200, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 144, min: 100, max: 200, step: 10 },
      deckStyle: { type: 'select', label: 'Deck Style', default: 'standard', options: ['standard', 'full-deck'] },
      maxLayers: { type: 'number', label: 'Max Layers', default: 5, min: 1, max: 15, step: 1 },
      rows: { type: 'number', label: 'Rows', default: 4, min: 1, max: 10, step: 1 },
      columns: { type: 'number', label: 'Columns', default: 3, min: 1, max: 10, step: 1 },
      productSpacing: { type: 'number', label: 'Product Spacing (mm)', default: 10, min: 0, max: 50, step: 5 },
      layerPattern: { type: 'select', label: 'Layer Pattern', default: 'aligned', options: ['aligned', 'interlocked', 'rotated'] },
    },
  },
  {
    id: 'standard-pallet',
    name: 'Standard Pallet',
    category: 'pallets',
    icon: SquareStack,
    description: 'Generic standard pallet (1000×1200mm)',
    parameters: {
      length: { type: 'number', label: 'Length (mm)', default: 1000, min: 600, max: 2000, step: 50 },
      width: { type: 'number', label: 'Width (mm)', default: 1200, min: 600, max: 2000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 150, min: 100, max: 250, step: 10 },
      deckStyle: { type: 'select', label: 'Deck Style', default: 'standard', options: ['standard', 'full-deck', 'open-deck'] },
      maxLayers: { type: 'number', label: 'Max Layers', default: 5, min: 1, max: 15, step: 1 },
      rows: { type: 'number', label: 'Rows', default: 3, min: 1, max: 10, step: 1 },
      columns: { type: 'number', label: 'Columns', default: 4, min: 1, max: 10, step: 1 },
      productSpacing: { type: 'number', label: 'Product Spacing (mm)', default: 10, min: 0, max: 50, step: 5 },
      layerPattern: { type: 'select', label: 'Layer Pattern', default: 'aligned', options: ['aligned', 'interlocked', 'rotated'] },
    },
  },
  {
    id: 'custom-pallet',
    name: 'Custom Pallet',
    category: 'pallets',
    icon: SquareStack,
    description: 'Fully configurable pallet dimensions',
    parameters: {
      length: { type: 'number', label: 'Length (mm)', default: 1000, min: 400, max: 3000, step: 50 },
      width: { type: 'number', label: 'Width (mm)', default: 1000, min: 400, max: 3000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 150, min: 50, max: 300, step: 10 },
      deckStyle: { type: 'select', label: 'Deck Style', default: 'standard', options: ['standard', 'full-deck', 'open-deck'] },
      maxLayers: { type: 'number', label: 'Max Layers', default: 5, min: 1, max: 20, step: 1 },
      rows: { type: 'number', label: 'Rows', default: 3, min: 1, max: 12, step: 1 },
      columns: { type: 'number', label: 'Columns', default: 3, min: 1, max: 12, step: 1 },
      productSpacing: { type: 'number', label: 'Product Spacing (mm)', default: 10, min: 0, max: 100, step: 5 },
      layerPattern: { type: 'select', label: 'Layer Pattern', default: 'aligned', options: ['aligned', 'interlocked', 'rotated'] },
      maxPalletHeight: { type: 'number', label: 'Max Pallet Height (mm)', default: 1800, min: 500, max: 3000, step: 100 },
    },
  },

  // ─── FMCG End-of-Line Equipment ──────────────────────────────
  {
    id: 'carton-erector',
    name: 'Carton Erector',
    category: 'fmcg',
    icon: Package,
    description: 'Automatic carton forming and erecting machine',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1200, min: 800, max: 2000, step: 50 },
      depth: { type: 'number', label: 'Depth (mm)', default: 800, min: 500, max: 1500, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 1800, min: 1200, max: 2500, step: 50 },
      cycleTime: { type: 'number', label: 'Cycle Time (s)', default: 3, min: 0.5, max: 30, step: 0.5 },
    },
  },
  {
    id: 'case-packer',
    name: 'Case Packer',
    category: 'fmcg',
    icon: Package,
    description: 'Automated case packing system for products into cases',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1500, min: 1000, max: 2500, step: 50 },
      depth: { type: 'number', label: 'Depth (mm)', default: 1000, min: 600, max: 2000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 2000, min: 1500, max: 2500, step: 50 },
      cycleTime: { type: 'number', label: 'Cycle Time (s)', default: 5, min: 1, max: 30, step: 0.5 },
      casesPerMinute: { type: 'number', label: 'Cases/min', default: 15, min: 5, max: 60, step: 1 },
    },
  },
  {
    id: 'checkweigher',
    name: 'Checkweigher',
    category: 'fmcg',
    icon: Database,
    description: 'Inline checkweigher for product weight verification',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 800, min: 500, max: 1200, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 900, min: 600, max: 1200, step: 50 },
      weightTolerance: { type: 'number', label: 'Tolerance (%)', default: 5, min: 0.5, max: 20, step: 0.5 },
      rejectEnabled: { type: 'boolean', label: 'Reject Enabled', default: true },
    },
  },
  {
    id: 'metal-detector',
    name: 'Metal Detector',
    category: 'fmcg',
    icon: Eye,
    description: 'Inline metal detection for product safety compliance',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 400, max: 1000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 900, min: 600, max: 1200, step: 50 },
      sensitivity: { type: 'select', label: 'Sensitivity', default: 'high', options: ['low', 'medium', 'high'] },
    },
  },
  {
    id: 'labeler',
    name: 'Labeler / Print & Apply',
    category: 'fmcg',
    icon: Wrench,
    description: 'Automatic label printer and applicator station',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 400, max: 1000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 1200, min: 800, max: 1600, step: 50 },
      labelSide: { type: 'select', label: 'Label Side', default: 'front', options: ['front', 'back', 'top', 'both-sides'] },
      labelsPerMin: { type: 'number', label: 'Labels/min', default: 40, min: 10, max: 200, step: 5 },
    },
  },
  {
    id: 'sealing-station',
    name: 'Sealing / Taping Station',
    category: 'fmcg',
    icon: Wrench,
    description: 'Carton sealing and tape application station',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 700, min: 500, max: 1000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 1000, min: 700, max: 1500, step: 50 },
      sealType: { type: 'select', label: 'Seal Type', default: 'tape', options: ['tape', 'glue', 'heat-seal'] },
    },
  },
  {
    id: 'reject-station',
    name: 'Reject Station',
    category: 'fmcg',
    icon: ArrowRightLeft,
    description: 'Pneumatic reject for failed product removal',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 400, max: 1000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 900, min: 600, max: 1200, step: 50 },
      rejectMethod: { type: 'select', label: 'Reject Method', default: 'pusher', options: ['pusher', 'air-blast', 'diverter', 'trap-door'] },
    },
  },
  {
    id: 'accumulation-table',
    name: 'Accumulation Table',
    category: 'fmcg',
    icon: SquareStack,
    description: 'Buffer/accumulation roller table for product staging',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 2000, min: 1000, max: 4000, step: 100 },
      depth: { type: 'number', label: 'Depth (mm)', default: 1500, min: 800, max: 3000, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 800, min: 500, max: 1200, step: 50 },
    },
  },
  {
    id: 'stretch-wrapper',
    name: 'Stretch Wrapper',
    category: 'fmcg',
    icon: RotateCw,
    description: 'Turntable stretch wrapper for pallet wrapping',
    parameters: {
      height: { type: 'number', label: 'Mast Height (mm)', default: 2500, min: 2000, max: 3500, step: 100 },
      wrapSpeed: { type: 'number', label: 'Wraps/min', default: 12, min: 5, max: 25, step: 1 },
      filmLayers: { type: 'number', label: 'Film Layers', default: 3, min: 1, max: 8, step: 1 },
    },
  },
  {
    id: 'packing-station',
    name: 'Operator Packing Station',
    category: 'fmcg',
    icon: Columns,
    description: 'Manual packing workstation with shelving and task light',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1500, min: 1000, max: 2500, step: 100 },
      depth: { type: 'number', label: 'Depth (mm)', default: 800, min: 600, max: 1200, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 900, min: 700, max: 1100, step: 50 },
    },
  },
  {
    id: 'pallet-conveyor',
    name: 'Pallet Conveyor',
    category: 'fmcg',
    icon: ArrowRight,
    description: 'Heavy-duty roller conveyor for pallet transport',
    parameters: {
      length: { type: 'number', label: 'Length (mm)', default: 3000, min: 1000, max: 6000, step: 500 },
      width: { type: 'number', label: 'Width (mm)', default: 1200, min: 800, max: 1600, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 500, min: 300, max: 800, step: 50 },
      speed: { type: 'number', label: 'Speed (m/min)', default: 8, min: 1, max: 20, step: 1 },
    },
  },
  {
    id: 'forklift',
    name: 'Forklift',
    category: 'fmcg',
    icon: ArrowUpDown,
    description: 'Static forklift representation for layout planning',
    parameters: {},
  },

  // ─── Medical / Cleanroom Equipment ────────────────────────────
  {
    id: 'stainless-conveyor',
    name: 'Stainless Conveyor',
    category: 'medical',
    icon: ArrowRight,
    description: 'Cleanroom-grade stainless steel belt conveyor',
    parameters: {
      length: { type: 'number', label: 'Length (mm)', default: 2000, min: 500, max: 5000, step: 100 },
      width: { type: 'number', label: 'Width (mm)', default: 400, min: 200, max: 800, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 800, min: 300, max: 1200, step: 50 },
      speed: { type: 'number', label: 'Speed (m/min)', default: 10, min: 1, max: 40, step: 1 },
    },
  },
  {
    id: 'laminar-flow-hood',
    name: 'Laminar Flow Hood',
    category: 'medical',
    icon: ArrowUp,
    description: 'ISO Class 5 laminar flow workstation with HEPA filtration',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1200, min: 900, max: 1800, step: 100 },
      depth: { type: 'number', label: 'Depth (mm)', default: 800, min: 600, max: 1000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 2200, min: 1800, max: 2500, step: 50 },
      isoClass: { type: 'select', label: 'ISO Class', default: '5', options: ['5', '6', '7'] },
    },
  },
  {
    id: 'clean-bench',
    name: 'Clean Bench / Worktable',
    category: 'medical',
    icon: Columns,
    description: 'Stainless steel cleanroom workbench with upstand',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1500, min: 800, max: 2500, step: 100 },
      depth: { type: 'number', label: 'Depth (mm)', default: 750, min: 500, max: 1000, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 850, min: 700, max: 1000, step: 50 },
    },
  },
  {
    id: 'pass-through-hatch',
    name: 'Pass-Through Hatch',
    category: 'medical',
    icon: ArrowRightLeft,
    description: 'Interlocked pass box for material transfer between zones',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 400, max: 1000, step: 50 },
      depth: { type: 'number', label: 'Depth (mm)', default: 600, min: 400, max: 800, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 600, min: 400, max: 800, step: 50 },
    },
  },
  {
    id: 'cleanroom-cart',
    name: 'Cleanroom Cart',
    category: 'medical',
    icon: ArrowUpDown,
    description: 'Stainless steel trolley with shelves and casters',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 600, min: 400, max: 1000, step: 50 },
      depth: { type: 'number', label: 'Depth (mm)', default: 400, min: 300, max: 700, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 900, min: 700, max: 1200, step: 50 },
      shelves: { type: 'number', label: 'Shelves', default: 3, min: 2, max: 5, step: 1 },
    },
  },
  {
    id: 'guard-partition',
    name: 'Guard Partition Panel',
    category: 'medical',
    icon: Columns,
    description: 'Cleanroom partition with solid lower + glass upper panel',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1200, min: 600, max: 2400, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 2100, min: 1800, max: 2500, step: 50 },
    },
  },
  {
    id: 'light-curtain',
    name: 'Light Curtain',
    category: 'medical',
    icon: Eye,
    description: 'Safety light curtain / scanner for zone protection',
    parameters: {
      height: { type: 'number', label: 'Height (mm)', default: 1500, min: 600, max: 2000, step: 50 },
      gap: { type: 'number', label: 'Gap (mm)', default: 1200, min: 500, max: 3000, step: 100 },
    },
  },
  {
    id: 'inspection-station',
    name: 'Inspection Station',
    category: 'medical',
    icon: Eye,
    description: 'Vision inspection system with camera + ring light',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 800, min: 500, max: 1200, step: 50 },
      height: { type: 'number', label: 'Height (mm)', default: 1200, min: 900, max: 1500, step: 50 },
    },
  },
  {
    id: 'machine-enclosure',
    name: 'Machine Enclosure',
    category: 'medical',
    icon: SquareStack,
    assetId: 'machine-enclosure',
    description: 'Cleanroom-grade machine guard enclosure with polycarbonate panels',
    parameters: {
      width: { type: 'number', label: 'Width (mm)', default: 1500, min: 800, max: 3000, step: 100 },
      depth: { type: 'number', label: 'Depth (mm)', default: 1200, min: 600, max: 2500, step: 100 },
      height: { type: 'number', label: 'Height (mm)', default: 2000, min: 1500, max: 2500, step: 50 },
    },
  },
];

export function getModuleDefinition(id: string): ModuleDefinition | undefined {
  return moduleLibrary.find(module => module.id === id);
}

export function getModulesByCategory(category: string): ModuleDefinition[] {
  return moduleLibrary.filter(module => module.category === category);
}